version: "3"

services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: ghcr.io/a13xie/spring-example:main
    depends_on: 
      - postgres
    ports:
      - 8080:8080
    restart: unless-stopped
